# Generated by Django 5.0.6 on 2024-06-18 20:27

import availability.models
import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('occupied', 'Occupied'), ('permanent', 'Permanent')], default='available', max_length=10)),
                ('room_type', models.CharField(choices=[('suite', 'Suite'), ('normal', 'Normal')], max_length=10)),
                ('ac_type', models.CharField(choices=[('ac', 'AC'), ('non_ac', 'Non AC')], max_length=10)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(help_text='Enter a 10-digit contact number.', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid 10-digit contact number.'), availability.models.validate_contact_length])),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PermanentBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_bookings', to='availability.room')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='availability.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('occupied', 'Occupied'), ('permanent', 'Permanent')], default='booked', max_length=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='availability.room')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='availability.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('status', models.CharField(choices=[('expired', 'Expired'), ('deleted', 'Deleted')], max_length=10)),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='availability.room')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='availability.tenant')),
            ],
        ),
    ]
