# Generated by Django 5.0.6 on 2024-06-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0004_archivedbooking_booking_id_archivedtenant_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedbooking',
            name='booking_id',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='archivedtenant',
            name='booking_id',
            field=models.CharField(max_length=1000),
        ),
    ]
