# Generated by Django 5.0.6 on 2025-01-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0006_alter_archivedbooking_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('occupied', 'Occupied')], default='booked', max_length=10),
        ),
    ]
