# Generated by Django 5.0.6 on 2025-01-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0007_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('occupied', 'Occupied')], default='booked', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='archivedtenant',
            unique_together={('name', 'contact', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='tenant',
            unique_together={('name', 'contact', 'email')},
        ),
    ]
