# Generated by Django 5.0.6 on 2025-01-20 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0008_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='archivedtenant',
            unique_together=set(),
        ),
    ]
