# Generated by Django 5.0.6 on 2025-01-20 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0009_alter_archivedtenant_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='archivedtenant',
            unique_together={('name', 'contact', 'email')},
        ),
    ]
