# Generated by Django 5.0.6 on 2025-01-21 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0010_alter_archivedtenant_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='permanentbooking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permanentbooking',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
