# Generated by Django 5.0.6 on 2025-01-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0011_permanentbooking_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedbooking',
            name='type',
            field=models.CharField(choices=[('temporary', 'Temporary'), ('permanent', 'Permanent')], default='temporary', max_length=10),
            preserve_default=False,
        ),
    ]
