# Generated by Django 5.0.6 on 2025-01-21 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0013_alter_permanentbooking_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permanentbooking',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
